- label: "Hello"
  message: "$payload.pull_request.user.login"
  color: "green"

- label: "Preview"
  message: "Closes #$prNumber"
  color: "blue"
  url: "https://github.com/yaooqinn/kyuubi/pull/$prNumber"

- label: "+"
  message: "$additions"
  color: "red"

- label: "-"
  message: "$deletions"
  color: "green"

- label: "commits"
  message: "$commits"
  color: "yellow"

- label: "Missing"
  message: "Target Issue"
  color: "#ff0000"
  when: "$payload.pull_request.title.includes('[KYUUBI #') === false"

- label: "Missing"
  message: "Test Plan"
  color: "#ff0000"
  when: "$payload.pull_request.body.includes('- [x]') === false"

- label: "Label"
  message: "Feature"
  when: "$labels.includes('Feature')"

- label: "Label"
  message: "Bug"
  when: "$labels.includes('Bug')"

- label: "Label"
  message: "Doc"
  when: "$labels.includes('document')"

- label: "Label"
  message: "Test"
  when: "$labels.includes('test')"
